import { useId } from 'react'

// Dot-grid teardrop: 13x17 grid, apex top / rounded bottom, 137 dots.
// Generated by scripts/_gen_dots.mjs (point-in-teardrop membership test).
const DOTS: [number, number][] = [
  [50, 8],
  [42.67, 15.5], [50, 15.5], [57.33, 15.5],
  [35.33, 23], [42.67, 23], [50, 23], [57.33, 23], [64.67, 23],
  [35.33, 30.5], [42.67, 30.5], [50, 30.5], [57.33, 30.5], [64.67, 30.5],
  [28, 38], [35.33, 38], [42.67, 38], [50, 38], [57.33, 38], [64.67, 38], [72, 38],
  [28, 45.5], [35.33, 45.5], [42.67, 45.5], [50, 45.5], [57.33, 45.5], [64.67, 45.5], [72, 45.5],
  [20.67, 53], [28, 53], [35.33, 53], [42.67, 53], [50, 53], [57.33, 53], [64.67, 53], [72, 53], [79.33, 53],
  [20.67, 60.5], [28, 60.5], [35.33, 60.5], [42.67, 60.5], [50, 60.5], [57.33, 60.5], [64.67, 60.5], [72, 60.5], [79.33, 60.5],
  [13.33, 68], [20.67, 68], [28, 68], [35.33, 68], [42.67, 68], [50, 68], [57.33, 68], [64.67, 68], [72, 68], [79.33, 68], [86.67, 68],
  [13.33, 75.5], [20.67, 75.5], [28, 75.5], [35.33, 75.5], [42.67, 75.5], [50, 75.5], [57.33, 75.5], [64.67, 75.5], [72, 75.5], [79.33, 75.5], [86.67, 75.5],
  [6, 83], [13.33, 83], [20.67, 83], [28, 83], [35.33, 83], [42.67, 83], [50, 83], [57.33, 83], [64.67, 83], [72, 83], [79.33, 83], [86.67, 83], [94, 83],
  [6, 90.5], [13.33, 90.5], [20.67, 90.5], [28, 90.5], [35.33, 90.5], [42.67, 90.5], [50, 90.5], [57.33, 90.5], [64.67, 90.5], [72, 90.5], [79.33, 90.5], [86.67, 90.5], [94, 90.5],
  [13.33, 98], [20.67, 98], [28, 98], [35.33, 98], [42.67, 98], [50, 98], [57.33, 98], [64.67, 98], [72, 98], [79.33, 98], [86.67, 98],
  [13.33, 105.5], [20.67, 105.5], [28, 105.5], [35.33, 105.5], [42.67, 105.5], [50, 105.5], [57.33, 105.5], [64.67, 105.5], [72, 105.5], [79.33, 105.5], [86.67, 105.5],
  [20.67, 113], [28, 113], [35.33, 113], [42.67, 113], [50, 113], [57.33, 113], [64.67, 113], [72, 113], [79.33, 113],
  [28, 120.5], [35.33, 120.5], [42.67, 120.5], [50, 120.5], [57.33, 120.5], [64.67, 120.5], [72, 120.5],
  [35.33, 128], [42.67, 128], [50, 128], [57.33, 128], [64.67, 128],
]

const DROP_PATH = 'M50 3 C 38 30 4 58 4 86 A 46 46 0 0 0 96 86 C 96 58 62 30 50 3 Z'

export function WaterDropMark({ className = 'w-8 h-8' }: { className?: string }) {
  const uid = useId().replace(/[^a-zA-Z0-9]/g, '')
  const gDot = `wp-dot-${uid}`
  const gInset = `wp-inset-${uid}`
  const gTint = `wp-tint-${uid}`
  const gClip = `wp-clip-${uid}`
  return (
    <svg
      className={className}
      viewBox="0 0 100 134"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      style={{ isolation: 'isolate' }}
    >
      <defs>
        <radialGradient id={gDot} cx="35%" cy="28%" r="80%">
          <stop offset="0%" stopColor="#ffffff" />
          <stop offset="35%" stopColor="#e8eef5" />
          <stop offset="70%" stopColor="#a8b4c4" />
          <stop offset="100%" stopColor="#55647a" />
        </radialGradient>
        <radialGradient id={gInset} cx="60%" cy="60%" r="72%">
          <stop offset="0%" stopColor="#0f172a" stopOpacity="0" />
          <stop offset="60%" stopColor="#0f172a" stopOpacity="0" />
          <stop offset="82%" stopColor="#0f172a" stopOpacity="0.18" />
          <stop offset="100%" stopColor="#0f172a" stopOpacity="0.5" />
        </radialGradient>
        <linearGradient id={gTint} x1="0" y1="0" x2="1" y2="0">
          <stop offset="0.3" stopColor="#2AB4F5" stopOpacity="0" />
          <stop offset="1" stopColor="#2AB4F5" stopOpacity="1" />
        </linearGradient>
        <clipPath id={gClip}>
          <path d={DROP_PATH} />
        </clipPath>
      </defs>
      <g>
        {DOTS.map(([x, y], i) => (
          <g key={i}>
            <circle cx={x} cy={y} r="2.6" fill={`url(#${gDot})`} />
            <circle cx={x} cy={y} r="2.6" fill={`url(#${gInset})`} />
          </g>
        ))}
      </g>
      <g clipPath={`url(#${gClip})`}>
        <rect
          x="20"
          y="0"
          width="80"
          height="134"
          fill={`url(#${gTint})`}
          style={{ mixBlendMode: 'color' }}
        />
      </g>
    </svg>
  )
}

/** @deprecated Name kept for compatibility; now the WaterPax dot teardrop */
export const PhlexMark = WaterDropMark
